---
minio:
    address: 0.0.0.0
    port: 9000
    accessKey: minioadmin
    secretKey: minioadmin
    ssl: false
    bucket: devbucket  # set to a bucket you own in your object store of choice
    region: us-east-1
gleaner:
    runid: myrun   # this will be the bucket the output is placed in...
    summon: true   # do we want to visit the web sites and pull down the files
    mill: false
context:
    cache: true
contextmaps:
    - prefix: "https://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org/"
      file: "./schemaorg-current-https.jsonld"
summoner:
    after: ""      # "21 May 20 10:00 UTC"
    mode: full     # full || diff:
    threads: 1
    delay: 1000  # ms (1000 = 1 sec) delay between calls (will FORCE threads to 1)
    headless: http://0.0.0.0:9222  # URL for headless see docs/headless
millers:
    graph: true
sources:
    - name: wod
      propername: World Ocean Database
      catalogue: https://noaa-wod-pds.s3.amazonaws.com/index.html
      domain: https://www.ncei.noaa.gov/products/world-ocean-database
      logo: https://www.ncei.noaa.gov/themes/custom/ncei/logo.svg
      pid: https://catalogue.odis.org/view/182
      sourcetype: sitemap
      url: https://raw.githubusercontent.com/iodepo/odis-arch/master/collection/tempHosting/data-wod/sitemap.xml
      changefreq:
      backend: AmazonS3
      headless: false
      dateadded: 2023-09-13
      cron: 0 15 * * 0
      active: true
