---
minio:
  address: 0.0.0.0
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
  ssl: false
  bucket: devbucket  # set to a bucket you own in your object store of choice
  region: us-east-1
implementation_network:
  orgname: iow
context:
  cache: true
  strict: true
contextmaps:
    - prefix: "https://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org/"
      file: "./schemaorg-current-https.jsonld"
objects:
  domain: us-east-1
  prefix:
    - prov/africaioc
    - summoned/africaioc
endpoints:
  - service: oxigraph
    baseurl: http://0.0.0.0:7878
    type: oxigraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /query
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /store
        accept: application/n-quads
        method: POST
      - action: bulk
        suffix: /store
        accept: application/n-quads
        method: POST
  - service: blazegraph_testing
    baseurl: http://coreos.lan:9090/blazegraph/namespace/testing
    type: blazegraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST

