services:

  triplestore:
    image: khaller/graphdb-free:latest
    restart: unless-stopped
    ports:
      - 7200:7200
    environment:
      JAVA_XMS: 2048m
      JAVA_XMX: 4g
    volumes:
      - ${GLEANER_GRAPH}/graphdb-home:/opt/graphdb-home
      - ${GLEANER_GRAPH}/graphdb-data:/opt/graphdb/data
      - ${GLEANER_GRAPH}/graphdb-import:/root/graphdb-import
      - ${GLEANER_GRAPH}/repository.init:/repository.init
    networks:
      - traefik_default

  s3system:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - 54321:54321
      - 9000:9000
    volumes:
      - ${GLEANER_OBJECTS}:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - traefik_default
    command: ["server", "/data", "--console-address", ":54321"]

  headless:
    image: chromedp/headless-shell:latest
    restart: unless-stopped
    labels:
      - "traefik.backend=headlesschrome"
      - "traefik.port=9222"
    ports:
      - 9222:9222
    environment:
     - SERVICE_PORTS=9222
    networks:
      - traefik_default

#  meili:
#    image: getmeili/meilisearch:latest
#    restart: unless-stopped
#    labels:
#      - "traefik.backend=headlesschrome"
#      - "traefik.port=7700"
#    volumes:
#      - ${GLEANER_MEILI}:/data.ms
#    ports:
#     - 7700:7700
#    environment:
#     - SERVICE_PORTS=7700
#    networks:
#      - traefik_default

  # features:
  #   image: fils/grow-general:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - S3ADDRESS=s3system:9000
  #     - S3BUCKET=sites
  #     - S3PREFIX=domain
  #     - DOMAIN=https://${GLEANER_WEB_DOMAIN}/
  #     - S3KEY=${MINIO_ACCESS_KEY}
  #     - S3SECRET=${MINIO_SECRET_KEY}
  #   networks:
  #     - traefik_default

networks:
  traefik_default: