---
version: '3'

services:

 #explorer:
  #image: localhost/graph-explorer:latest
  #environment:
    #- HOST=localhost
      ##  volumes:
    ##- ./nginx.conf:/etc/nginx/nginx.conf
    ### For multiple users: uncomment this line to mount a pre-generated .htpasswd 
    ## podman run --group-add keep-groups  --env HOST=ghost.lan --privileged  -v ./config.json:/graph-explorer/config.json  -p 80:80 -p 443:443 -p 8182:8182 localhost/graph-explorer:latest
    ## - ./.htpasswd:/etc/nginx/.htpasswd
  #ports:
    #- "80:80"
    #- "443:443"
    #- "8182:8182"

 t1:
  image: oxigraph/oxigraph
  restart: unless-stopped
  ports:
    - 7878:7878
  volumes:
    - ./data/triplestore:/data

