direction: right


title:  |md
  # UNESCO/IODE/ODIS/OIH Data Operations

| { near: top-center }

classes: {
od: {
    width: 300
               style: {
                     stroke-width: 0
                    fill: "#44C7B1"
                    shadow: true
                    border-radius: 5
               }
      }

oih: {
    width: 300
               style: {
                     stroke-width: 0
                    fill: lightblue
                    shadow: true
                    border-radius: 5
               }
      }

oihservice : {
    width: 300
               style: {
                     stroke-width: 0
                    fill: "#FF2400"
                    shadow: true
                    border-radius: 5
               }
      }


oihgroup: {
               style: {
                     stroke-width: 0
                    fill: honeydew
                    shadow: true
                    border-radius: 5
               }
      }

}

kg: Knowledge Graph {
   class: oih
    }

net: Graph Network {
   class: oih
}

mdp: Query generated \n  Master Data Product {
class:oih

     }

ti: Text or Vector Index  {
      class:oih
    }

sp: Spatial index {
    class:oih
    }

ml: Machine Learning Worflow {
class: oih
    }

kg -> net
kg -> mdp

mdp -> ti

kg -> sp
mdp -> sp

kg -> ml
mdp -> ml

# services

ddb: DuckDB {
class: oihservice
}

ts: TripleStore / SPARQL {
class:  oihservice
    }

geo: GeoAPI {
class: oihservice
     }

kg -> ts
mdp -> ddb
sp -> geo
