---
minio:
    address: 192.168.202.114
    port: 49153
    accessKey:
    secretKey:
    ssl: false
    bucket: gleaner.oih
gleaner:
    runid: runx    # this will be the bucket the output is placed in...
    summon: true   # do we want to visit the web sites and pull down the files
    mill: false
context:
    cache: true
contextmaps:
    - prefix: "https://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org/"
      file: "./schemaorg-current-https.jsonld"
summoner:
    after: ""      # "21 May 20 10:00 UTC"
    mode: full     # full || diff:
    threads: 5
    delay:  # ms (1000 = 1 sec) delay between calls (will FORCE threads to 1)
    headless: http://0.0.0.0:9222  # URL for headless see docs/headless
millers:
    graph: true
sources:
    - name: africaioc
      propername: IOC Africa Data Portal
      catalogue: https://ioc-africa.org/dbs/displayData.php
      domain: https://ioc-africa.org
      logo: https://ioc-africa.org/dbs/images/unesco_ioc_logo.png
      pid: https://oceaninfohub.org/.well-known/org/africaioc
      sourcetype: sitemap
      url: https://ioc-africa.org/sitemap.xml
      changefreq: daily
      backend: Custom
      headless: false
      dateadded: 2023-02-09
      active: true
    - name: medin
      propername: Marine Environmental Data and Information Network (MEDIN)
      catalogue: https://portal.medin.org.uk/portal/start.php
      domain: https://medin.org.uk/
      logo: https://medin.org.uk/sites/medin/files/images/medin-portal-logo.png
      pid: https://catalogue.odis.org/view/40
      sourcetype: sitemap  
      url: https://portal.medin.org.uk/portal/sitemap.php
      changefreq: daily
      backend: MARIS
      headless: false
      dateadded: 2023-05-11
      active: true     
    - name: oceanscape
      propername: Oceanscape Project
      catalogue: https://oceanscape.org
      domain: https://geoblueplanet.org/
      logo: https://oceanscape.org/wp-content/uploads/2019/06/Oceanscape-banner-1024x183.png
      pid: https://catalogue.odis.org/view/1098
      sourcetype: sitemap
      url: https://oceanscape.org/organisation-sitemap.xml
      changefreq: as needed
      backend: WordPress
      headless: false
      dateadded: 2022-05-18
      active: true
    - name: rda
      propername: Research Data Australia
      catalogue: https://researchdata.edu.au/
      domain: https://ardc.edu.au/
      logo: https://researchdata.edu.au/assets/img/ARDC_Research_Data_RGB_FA_Reverse_sml.png
      pid: https://catalogue.odis.org/view/3267
      sourcetype: sitemap
      url: https://researchdata.edu.au/home/sitemap/?ds=384
      changefreq: daily
      backend: GeoNetwork
      headless: false
      dateadded: 2023-03-06
      active: true
    - name: cioos
      propername: CIOOS
      catalogue: https://catalogue.cioos.ca/
      domain: https://cioos.ca/
      logo: https://cioos.ca/wp-content/themes/cioos-siooc-wordpress-theme/img/national/cioos-national_EN.svg
      pid: https://catalogue.odis.org/view/3263
      sourcetype: sitemap
      url: https://catalogue.cioos.ca/sitemap/sitemap.xml
      changefreq: daily
      backend: CKAN
      headless: false
      dateadded: 2023-01-31
      active: true
