---
minio:
    address: 0.0.0.0
    port: 9000
    accessKey: minioadmin
    secretKey: minioadmin
    ssl: false
    bucket: devbucket  # set to a bucket you own in your object store of choice
    region: us-east-1
gleaner:
    runid: myrun   # this will be the bucket the output is placed in...
    summon: true   # do we want to visit the web sites and pull down the files
    mill: false
context:
    cache: true
contextmaps:
    - prefix: "https://schema.org/"
      file: "./schemaorg-current-https.jsonld"
    - prefix: "http://schema.org/"
      file: "./schemaorg-current-https.jsonld"
summoner:
    after: ""      # "21 May 20 10:00 UTC"
    mode: full     # full || diff:
    threads: 5
    delay:  # ms (1000 = 1 sec) delay between calls (will FORCE threads to 1)
    headless: http://0.0.0.0:9222  # URL for headless see docs/headless
millers:
    graph: true
sources:
    - name: bcodmo
      propername: BCO-DMO
      catalogue: https://www.bco-dmo.org/
      domain: https://www.bco-dmo.org/
      logo: https://www.bco-dmo.org/sites/all/themes/bcodmo/logo.png
      #ODISCat entry missing ODIS-arch url
      pid: https://catalogue.odis.org/view/3287
      sourcetype: sitemap
      url: https://www.bco-dmo.org/sitemap.xml
      changefreq: weekly
      backend: unknown
      headless: false
      dateadded: 2021-02-26
      active: true
      cron: 0 19 * * 0
    - name: obis
      propername: Ocean Biodiversity Information System
      catalogue: https://obis.org
      domain: https://obis.org
      logo: https://obis.org/images/logo.png
      #ODISCat entry missing ODIS-arch url
      pid: https://catalogue.odis.org/view/343
      sourcetype: sitemap
      url: https://obis.org/sitemap_datasets.xml
      changefreq: weekly
      backend: unknown
      headless: false
      dateadded: 2021-02-26
      active: true
      cron: 0 19 * * 0
    - name: edmo
      propername: European Directory of Marine Organisations (EDMO) SeaDataNet
      catalogue: https://edmo.seadatanet.org/search
      domain: https://edmo.seadatanet.org
      logo: https://edmo.seadatanet.org/grfx/edmo/logo.png
      #missing ODISCat entry
      pid: https://oceaninfohub.org/.well-known/org/edmo
      sourcetype: sitemap
      url: https://edmo.seadatanet.org/sitemap.xml
      changefreq: as needed
      backend: SeaDataCloud
      dateadded: 2021-07-26
      headless: false
      cron: 0 5 * * 0
      active: true
    - name: bodc
      propername: BODC
      catalogue: https://api.linked-systems.uk
      domain: https://api.linked-systems.uk
      logo: https://api.linked-systems.uk/logo.png
      pid: https://catalogue.odis.org/view/3263
      sourcetype: sitemap
      url: https://api.linked-systems.uk/sitemap_pap_api.xml
      changefreq: daily
      backend: Custom
      headless: false
      dateadded: 2023-01-31
      active: true