---
minio:
  address: s3.amazonaws.com
  port: 443
  accessKey:
  secretKey:
  ssl: true
  bucket: yourbucketname  # set to a bucket you own in your object store of choice
  region: us-east-1
implementation_network:
  orgname: iow
context:
  cache: true
  strict: true
contextmaps:
  - prefix: https://schema.org/
    file: ./assets/schemaorg-current-https.jsonld
  - prefix: http://schema.org/
    file: ./assets/schemaorg-current-http.jsonld
objects:
  domain: us-east-1
  prefix:
    - prov/source1
    - summoned/source1
endpoints:
  - service: oxigraph
    baseurl: http://coreos.lan:9090/blazegraph/namespace/testing
    type: oxigraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST
  - service: blazegraph_testing
    baseurl: http://coreos.lan:9090/blazegraph/namespace/testing
    type: blazegraph
    authenticate: false
    username:
    password:
    modes:
      - action: sparql
        suffix: /sparql
        accept: application/sparql-results+json
        method: GET
      - action: update
        suffix: /sparql
        accept: application/sparql-update
        method: POST
      - action: bulk
        suffix: /sparql
        accept: text/x-nquads
        method: POST

