minio:
  address: 192.168.202.114
  port: 49155
  accessKey: AKIAIOSFODNN7EXAMPLE
  secretKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  ssl: false
  bucket: gleaner.eco
gleaner:
  runid: ecotest
  summon: true # do we want to visit the web sites and pull down the files
  mill:  false
context:
  cache: true
contextmaps:
- prefix: "https://schema.org/"
  file: "./jsonldcontext.json"  # wget http://schema.org/docs/jsonldcontext.jsonld
- prefix: "http://schema.org/"
  file: "./jsonldcontext.json"  # wget http://schema.org/docs/jsonldcontext.jsonld
summoner:
  after: ""      # "21 May 20 10:00 UTC"   
  mode: full  # full || diff:  If diff compare what we have currently in gleaner to sitemap, get only new, delete missing
  threads: 10
  delay: 0  # milliseconds (1000 = 1 second) to delay between calls (will FORCE threads to 1) 
  headless: http://ghost.lan:9222  # URL for headless see docs/headless
millers:
  graph: false
sources:
- sourcetype: sitemap
  name: ecotest
  url: https://earthcube.github.io/GeoCODES-Metadata/metadata/Dataset/allgood/sitemap.xml
  headless: false
  pid: https://www.re3data.org/repository/r3d100012894
  properName: ecotest
  domain: domain
  active: true
